spring:
    main:
        allow-bean-definition-overriding: true
    profiles:
        active: local
        group:
          local: redis

---

spring:
    mvc:
        servlet:
            load-on-startup: 1
    config:
        activate:
            on-profile: local
    batch:
        jdbc:
            initialize-schema: always
        job:
            enabled: false
    datasource:
        url: jdbc:mysql://localhost:3306/gi_base?serverTimezone=Asia/Seoul
        username: gi-owner
        password: gi-owner
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
                default_batch_fetch_size: 1000
    jwt:
        jwt-access-secret-key: weareadmininplanningo
        jwt-refresh-secret-key: ogninnalpninimdaeraew
        temp-email-auth-secret-key: temporary-email-auth-plannigo
        jwt-access-expiration-in-ms: 259200000
        jwt-refresh-expiration-in-ms: 2419200000
